[package]
edition = "2018"
name = "addon"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
aes = "0.7.4"
block-modes = "0.8.1"
napi = "1"
napi-derive = "1"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
